using AdventOfCode2024.Solutions;

namespace AdventOfCode2024.Tests.Solutions;

public class Day08Tests
{
    private const string ExampleInput = @"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";
    
    [Fact]
    public void PartOneExample()
    {
        var result = new Day08().PartOne(ExampleInput);
        
        Assert.Equal(14, result);
    }

    [Fact]
    public void PartTwoExample()
    {
        var result = new Day08().PartTwo(ExampleInput);
        
        Assert.Equal(34, result);
    }
    
    [Fact]
    public void PartTwoExampleTwo()
    {
        var result = new Day08().PartTwo(@"T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........");
        
        Assert.Equal(9, result);
    }
}